### ISSUE TITLE
Unable to utilize workspace names with the workspace directive.

### ISSUE THREAD

**Issue by jtcrank** [regolith-linux/regolith-desktop#158]
When using the workspace directive in i3 config or via i3-msg, I am unable to use the workspace name or index as the parameter for the action. For example:
`workspace 1 output eDP-1-1` only works after switching to the workspace using the keybinding first. (see below related link)

This issue also become problematic for me when trying to set the layout.
`i3-msg "workspace 1"; append_layout /path/to/layout.json"`
opens up the layout in a workspace labeled "1" without the color box. In both of these examples, I would have expected it to bind the ws or open a layout to the "1 [ ]" workspace and not a new "1" workspace. Perhaps I am utilizing these wrong, and if so I would appreciate a nudge in the right direction.

I have attempted to use the `$ws1` variable with no success as well.

Link to what I believe is a related comment: https://github.com/regolith-linux/regolith-desktop/issues/84#issuecomment-520169715

**Comment by kgilmer** [comment]
Have a look at the responses in Slack and let us know if those don't work.

**Comment by leosunmo** [comment]
I think this might help @jtcrank, https://github.com/regolith-linux/regolith-i3-gaps-config/pull/1.

Take a look at the `number` directive I use there. There's some outstanding weirdness that's been fixed in the latest version of i3gaps. Give it a try and see if that works better for you.

**Comment by kgilmer** [comment]
This update (i3-gaps-wm - 4.17.1-1ubuntu1~ppa4) is currently building into `regolith-stable`.  Kindly re-open if after the update the problem isn't resolved @jtcrank .

**Comment by gnzlbg** [comment]
I ran into this issue while porting my i3 config to regolith:

In my `.config/regolith/i3/config` file I've added:

```
exec --no-startup-id ~/.config/regolith/i3/layout
```

where `layout` is defined as:

```bash
#!/usr/bin/env sh

i3-msg "workspace 1"; append_layout ~/.config/regolith/i3/ws1.json"
google-chrome --app=google.com &
google-chrome --app=soundcloud.com &
spotify &
slack &
```

The problem is that `workspace 1` does not refer to the first workspace in regolith (it creates a new workspace). This issue does not contain the solution to this problem, nor I can find it in the documentation.

**Comment by kgilmer** [comment]
How about this?

```
#!/usr/bin/env sh

i3-msg "workspace number 1; append_layout ~/.config/regolith/i3/ws1.json"
google-chrome --app=google.com &
spotify &
```

**Comment by gnzlbg** [comment]
Thanks! `workspace number 1` works perfectly!
