### ISSUE TITLE
Login Loop

### ISSUE THREAD

**Issue by K-Kouts** [regolith-linux/regolith-desktop#257]
Hello, i am using Regolith unstable version on Ubuntu 19.10. Everything was smooth until one time, all of a sudden, i could not login using Regolith, as it causes a login loop. Logging in with regular Ubuntu works fine. Please guide me as to which file outputs I should provide and/or next steps. Thanks in advance!

**Comment by kgilmer** [comment]
Hi @K-Kouts , do you have custom i3 config or Xresources?  There is probably an error in your `/var/log/syslog` file, but if you want to get fixed up quickly I suggest re-install of Regolith from the Ubuntu session, as described here: https://regolith-linux.org/docs/getting-started/install/#reinstallation

**Comment by K-Kouts** [comment]
Hi @kgilmer. Thank you for your answer. I deleted my Xresources file trying to fix this issue, but it did not work. I re-installed as the guide describes, but the issue is still there...

**Comment by kgilmer** [comment]
What does `apt policy | grep regolith` say?  Can you send me your /var/log/syslog? You can DM me privately on slack or email me at kgilmer at Gmail if you'd prefer to keep the file contents private.

**Comment by kgilmer** [comment]
Closing as I believe we fixed this over email.

**Comment by dustinromey** [comment]
Having a similar issue, can you elaborate on the fix?

**Comment by kgilmer** [comment]
HI @dustinromey , this issue was due to a bug in `unstable` that's since been fixed.  Please DM or email me your syslog and `apt list --installed` contents.  To quickly get the session restored, follow these re-installation steps: https://regolith-linux.org/docs/getting-started/install/#reinstallation

**Comment by kgilmer** [comment]
A user reported login issues from a Regolith session on Zorin OS.  A fix is available in PPA:regolith-linux/stable for testing.

**Comment by dustinromey** [comment]
Still having some issue here.

Here's what I can do right now:
- Reboot, open tty (ctrl-alt-F2)login and 'startx', get to a gnome environment

Things I can't do:

- start a session from the normal login screen; it just flashes for a second and goes back to the login screen
- From the terminal tty: 'xinit' or 'xinit -- :1' - crashes saying there may be another X server running

Things I've tried:
- Reinstall regolith
- Change to unstable ppa
- Change to stable ppa
- Change back to release ppa

I'm on POP OS 19.10, kernel 5.3

**Comment by kgilmer** [comment]
Hi @dustinromey , when you say you can't start a session, do you mean any session or only Regolith?

**Comment by kgilmer** [comment]
From the files you emailed me, you're definitely going to want to update your Regolith packages.  For example you have `regolith-gnome-flashback/eoan,now 2.4.1-1ubuntu1~ppa1 amd64` and the current version in release is `regolith-gnome-flashback - 2.4.5-1ubuntu1~ppa1`.  This package in particular has fixes that you likely need to run properly on Pop!_OS.

**Comment by dustinromey** [comment]
I can't start any session from the login screen. I can start a gnome session from a terminal.

regolith-gnome-flashback appears to be version 2.4.5. Here's the apt list output:

```
regolith-compositor-compton-glx/eoan,now 1.0.5-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-desktop/eoan,now 2.49-1ubuntu1~ppa1 amd64 [installed]
regolith-ftue/eoan,now 1.0.3-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-gnome-flashback/eoan,now 2.4.1-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-i3-gaps-config/eoan,now 2.3.4-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-i3xrocks-config/eoan,now 2.2.14-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-look-cahuella/eoan,now 2.3.5-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-rofication/eoan,now 1.0.9-1ubuntu1~ppa1 amd64 [installed,automatic]
regolith-st/eoan,now 0.8.2-1ubuntu20ppa5 amd64 [installed,automatic]
regolith-styles/eoan,now 2.3.5-1ubuntu1~ppa1 amd64 [installed,automatic]
```

**Comment by dustinromey** [comment]
I've completely removed and re-installed regolith various times using this procedure: [](https://regolith-linux.org/docs/getting-started/install/#reinstallation)

Currently on the stable ppa.

Wouldn't that mean I'm on all the up to date versions of regolith?

**Comment by kgilmer** [comment]
# Version issue
Setting the `stable` PPA and running `sudo apt update && sudo apt upgrade` should result in the latest Regolith package versions, but it looks like on your system this is not happening.  Your regolith-gnome-flashback version: regolith-gnome-flashback/eoan,now 2.4.1  [Current version in release](https://launchpad.net/~regolith-linux/+archive/ubuntu/release):  regolith-gnome-flashback - 2.4.5-1ubuntu1~ppa1.  I do not know why you would be unable to update.

# Session issue
If no sessions are loading, then that may point to a more serious issue outside of Regolith.  If you can send me your `/var/log/syslog` I can take a look but no promises that I can root-cause your problem.  If I were you at this point I'd backup and reinstall the OS.

**Comment by dustinromey** [comment]
Okay, luckily I've installed a couple of machines lately, so that's not too painful. Probably easier than endless trouble shooting.

Thanks for the help. Regolith is great.

**Comment by manugildev** [comment]
So... I have started having this error. I didn't change anything on my config and suddenly I couldn't boot without getting the annoying login loop that some of the other users were experiencing.

This is my [/var/log/syslog ](
https://github.com/manugildev/dotfiles/blob/main/syslog) file.

My username is manugil. It does not work with ubuntu-sessions either, same loop.

I tried reinstalling the regolith-linux with no luck, in neither stable nor release. Any help would be appreciated @kgilmer!

**Comment by manugildev** [comment]
> So... I have started having this error. I didn't change anything on my config and suddenly I couldn't boot without getting the annoying login loop that some of the other users were experiencing.

Solved. The problem was my ~/.profile entering a infinite loop.

**Comment by twitu** [comment]
I'm facing login loop issue with regolith 3.1 when trying to login with Wayland. Login with X11 works though. I'm on Ubuntu 22.04. Please let me know if I can share any details to help fix this.
