### ISSUE TITLE
Inconsistent theme for GTK dialogs

### ISSUE THREAD

**Issue by kgilmer** [regolith-linux/regolith-desktop#649]
Some dialogs appear light, others dark on Ubuntu Jammy (possibly others)

From slack:

```
[Karol Hennessy](https://app.slack.com/team/U01389AJH88)
  [3 days ago](https://regolith-linux.slack.com/archives/CLYDFU3JR/p1654958688914529?thread_ts=1654951848.795499&cid=CLYDFU3JR)
I think I found the solution.  I can set the gnome colour scheme via :
gsettings set org.gnome.desktop.interface color-scheme prefer-dark  or prefer-light
```

**Comment by kgilmer** [comment]
Seems to be something from `gnome-flashback`: https://gitlab.gnome.org/GNOME/gnome-flashback/-/issues/81

**Comment by lolwat97** [comment]
The fix didn't work for me.
```
╰─$ gsettings get org.gnome.desktop.interface color-scheme
'prefer-dark'
```
The dialogues, such as lockscreen password prompt and, for example, Discord file picker remain light-themed.
Normal Nautilus (if launched as a program) and other GTK stuff is dark-themed.

I'm running Pop OS 22.04 LTS, with regolith installed from the regolith repositories.

My Xresources:
```
regolith.look.path: /usr/share/regolith-look/blackhole
regolith.wallpaper.file: <redacted>

i3-wm.gaps.inner.size: 20
i3-wm.gaps.outer.size: 0

i3-wm.program.unclutter: :

i3-wm.bar.position: top
```

What additional info can I provide to help?

**Comment by lolwat97** [comment]
Seems like running a full system update fixed the password prompt theme for me. Here are the versions of packages now installed on my system, just for info:
```
╰─$ apt list | grep gnome-flashback

gnome-flashback-common/jammy,jammy,now 3.44.0-1ubuntu1 all [installed,automatic]
gnome-flashback/jammy,now 3.44.0-1ubuntu1 amd64 [installed,automatic]
```
```
╰─$ apt list regolith-desktop
regolith-desktop/unknown,now 4.1.0-1-1regolith amd64 [installed]
```
Some dialogues (like the discord filepicker) are still light-themed though.

**Comment by ilivss** [comment]
I don't use regolith-desktop but [this](https://github.com/regolith-linux/i3-gnome-flashback) package, which is part of regolith-desktop, instead. 

What I notice is that it isn't just the dialog theme that is inconsistent. It's actually the color theme of all gnome-flashback related GUI. E.g. the notification tray and notification popups, which are shipped with gnome-flashback, are sometimes white. 

I couldn't find out what triggers this behavior. Sometimes the gnome-flashback GUI is white on boot, sometimes it's dark. Sometimes it changes to white after a lock or suspend and sometimes not.

I have done the following to change the color schemes:
```
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
gsettings set org.gnome.desktop.interface gtk-theme 'Yaru-blue-dark'
```

I think we just need to wait until the upstream bug @kgilmer metioned is fixed.

**Comment by lolwat97** [comment]
By the way, shouldn't volume change popups also be themed? They're also white-ish for me.

**Comment by kgilmer** [comment]
The fix is available now in `jammy-proposed`.  I have not seen a problem since taking the update.

![image](https://user-images.githubusercontent.com/49683/180118966-f9aac400-f3df-48b3-8d6a-536cb77ee29d.png)

**Comment by p3k** [comment]
hm i installed the pre-release update but still see the light dialogs:

```
❯ apt search regolith-desktop
Sorting... Done
Full Text Search... Done
regolith-desktop/unknown,now 4.2.0-1regolith amd64 [installed]
  metapackage for Regolith desktop environment
```

![Screenshot from 2022-07-22 20-03-56](https://user-images.githubusercontent.com/16631/180498020-d92092bf-df9f-4496-ba98-42c6349c7ed0.png)

**Comment by p3k** [comment]
just a short update: between logins, the theme erratically switches between the correct dark mode and the incorrect light mode as seen in the screenshot above.

any idea what could be going on @kgilmer? anything i could post to provide more information?

**Comment by kgilmer** [comment]
What distro/release are you using @p3k .  What version of `gnome-flashback` do you have installed?

**Comment by p3k** [comment]
oh my bad timing as plenty of times: just shortly after my yesterday’s posting i ran `apt upgrade` and saw gnome-flashback mentioned in the listing of upgradable packages:

```plain
Unpacking gnome-flashback (3.44.0-1ubuntu2) over (3.44.0-1ubuntu1) ...
```

wanted to check after another reboot / first login and what can is say: indeed, for the first time the logout alert, volume control etc. appeared in dark mode right afterwards.

i think the version string of gnome-flashback did not change, afair:

```plain
❯ gnome-flashback -v
gnome-flashback 3.44.0

# distro / release for the record:
❯ lsb_release -ds; uname -smor
Ubuntu 22.04.1 LTS
Linux 5.15.0-46-generic x86_64 GNU/Linux
```

anyway, thanks for your feedback, @kgilmer. gonna evaluate some more reboots and if this remans the status quo now, i am going to close this issue.

**Comment by laluka** [comment]
Hello & sorry for reviving this bug! :sweat: 
Even with the following commands and the dark theme chosen from gnome settings (+ gnome tweaks checked), and the following commands applied, I can't get Regolith (under Ubuntu 24.04) to use the dark scheme, it seems overriden by the theme or something..

![image](https://github.com/user-attachments/assets/1e871aac-54a3-478c-9359-41cbc2b83b0a)

Here is some additional context:

```
regolith-diagnostic | grep -iP 'ligh|version|dark'
--- /etc/regolith/version:
REGOLITH_VERSION=3.2
Xft.hintstyle:	hintslight
regolith.lockscreen.wallpaper.file:	/usr/share/regolith-look/nord/nord-dark.png
Binary i3 version:  4.23 (2023-10-29) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.23 (2023-10-29) (pid 3623)
org.gnome.desktop.interface color-scheme 'prefer-dark'
org.gnome.desktop.interface font-hinting 'slight'
org.gnome.desktop.interface gtk-color-palette 'black:white:gray50:red:purple:blue:light blue:green:yellow:orange:lavender:brown:goldenrod4:dodger blue:pink:light green:gray10:gray30:gray75:gray90'
org.gnome.desktop.background picture-uri-dark 'file:///usr/share/backgrounds/gnome/adwaita-d.jpg'
org.gnome.settings-daemon.plugins.media-keys keyboard-brightness-toggle-static ['XF86KbdLightOnOff']
```

I'm not sure whether the issue lies in Ubuntu 24.04 (which was/is a pain to adopt), or from a theme applied, or the color palette overriding stuff... 
For more context: All the code to reproduce the issue can be found in the offensive regolith & mise-en-place based distro I maintain: https://github.com/laluka/lalubuntu :rose: 

Cheers!
